// controllers/adminController.js

const getUserList = async (req, res) => {
  try {
    // Dummy data for testing
    const users = [
      {
        id: 1,
        name: "John Smith",
        email: "john.smith@example.com",
        role: "student",
        status: "active",
        joinedDate: "2024-01-15",
        lastLogin: "2024-01-18",
        studentId: "S2024001",
      },
      {
        id: 2,
        name: "Jane Doe",
        email: "jane.doe@example.com",
        role: "faculty",
        status: "active",
        joinedDate: "2023-08-20",
        lastLogin: "2024-01-18",
        facultyId: "F2023001",
      },
      {
        id: 3,
        name: "Robert Johnson",
        email: "robert.j@example.com",
        role: "student",
        status: "inactive",
        joinedDate: "2024-01-10",
        lastLogin: "2024-01-12",
        studentId: "S2024002",
      },
      {
        id: 4,
        name: "Sarah Williams",
        email: "sarah.w@example.com",
        role: "admin",
        status: "active",
        joinedDate: "2023-09-15",
        lastLogin: "2024-01-18",
        adminId: "A2023001",
      },
      {
        id: 5,
        name: "Michael Brown",
        email: "michael.b@example.com",
        role: "student",
        status: "suspended",
        joinedDate: "2024-01-05",
        lastLogin: "2024-01-08",
        studentId: "S2024003",
      },
      {
        id: 6,
        name: "Emily Davis",
        email: "emily.d@example.com",
        role: "faculty",
        status: "active",
        joinedDate: "2023-10-10",
        lastLogin: "2024-01-18",
        facultyId: "F2023002",
      },
      {
        id: 7,
        name: "David Wilson",
        email: "david.w@example.com",
        role: "student",
        status: "pending",
        joinedDate: "2024-01-16",
        lastLogin: "2024-01-16",
        studentId: "S2024004",
      },
      {
        id: 8,
        name: "Lisa Taylor",
        email: "lisa.t@example.com",
        role: "faculty",
        status: "inactive",
        joinedDate: "2023-11-05",
        lastLogin: "2023-12-20",
        facultyId: "F2023003",
      },
    ];

    // Return JSON response
    res.status(200).json(users);
  } catch (error) {
    console.error("Error in getUserList:", error);
    res.status(500).json({ message: "Server error" });
  }
};

const getCourseList = async (req, res) => {
  try {
    const initialCourses = [
      {
        id: 1,
        code: "BSCS",
        name: "Bachelor of Science in Computer Science",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 2,
        code: "CSS",
        name: "Computer System Servicing NC II",
        type: "Short Course",
        started_date: "2024-01-15",
        end_date: "2024-06-15",
        status: "active",
      },
      {
        id: 3,
        code: "BSIT",
        name: "Bachelor of Science in Information Technology",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 4,
        code: "HUMSS",
        name: "Humanities and Social Sciences",
        type: "2 years Course",
        started_date: "2024-01-20",
        end_date: "2026-01-20",
        status: "active",
      },
      {
        id: 5,
        code: "STEM",
        name: "Science, Technology, Engineering and Mathematics",
        type: "2 years Course",
        started_date: "2024-02-01",
        end_date: "2026-02-01",
        status: "inactive",
      },

      // ➕ Additional 20 dummy courses

      {
        id: 6,
        code: "ABENG",
        name: "Bachelor of Arts in English",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 7,
        code: "ABPSY",
        name: "Bachelor of Arts in Psychology",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 8,
        code: "BSA",
        name: "Bachelor of Science in Accountancy",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 9,
        code: "BSBA",
        name: "Bachelor of Science in Business Administration",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 10,
        code: "BSTM",
        name: "Bachelor of Science in Tourism Management",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 11,
        code: "BSHM",
        name: "Bachelor of Science in Hospitality Management",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 12,
        code: "BSED",
        name: "Bachelor of Secondary Education",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 13,
        code: "BEED",
        name: "Bachelor of Elementary Education",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 14,
        code: "ICT",
        name: "Information and Communications Technology",
        type: "2 years Course",
        started_date: "2024-01-15",
        end_date: "2026-01-15",
        status: "active",
      },
      {
        id: 15,
        code: "EIM",
        name: "Electrical Installation and Maintenance NC II",
        type: "Short Course",
        started_date: "2024-02-01",
        end_date: "2024-07-01",
        status: "inactive",
      },
      {
        id: 16,
        code: "SMAW",
        name: "Shielded Metal Arc Welding NC II",
        type: "Short Course",
        started_date: "2024-03-01",
        end_date: "2024-08-01",
        status: "active",
      },
      {
        id: 17,
        code: "BSCHE",
        name: "Bachelor of Science in Chemical Engineering",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 18,
        code: "BSME",
        name: "Bachelor of Science in Mechanical Engineering",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 19,
        code: "BSEE",
        name: "Bachelor of Science in Electrical Engineering",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 20,
        code: "BSCIV",
        name: "Bachelor of Science in Civil Engineering",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 21,
        code: "BSN",
        name: "Bachelor of Science in Nursing",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 22,
        code: "BSPH",
        name: "Bachelor of Science in Pharmacy",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
      {
        id: 23,
        code: "RADTECH",
        name: "Radiologic Technology",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 24,
        code: "CRIM",
        name: "Bachelor of Science in Criminology",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "active",
      },
      {
        id: 25,
        code: "ABCOMM",
        name: "Bachelor of Arts in Communication",
        type: "4 years Course",
        started_date: "2023-09-01",
        end_date: "2027-06-30",
        status: "inactive",
      },
    ];

    res.status(200).json(initialCourses);
  } catch (error) {
    console.error("Error in getUserList:", error);
    res.status(500).json({ message: "Server error" });
  }
};

export { getUserList, getCourseList };
