// mockReviewQueueData.js
export const mockReviewQueue = [
  {
    id: 1,
    studentName: "John Doe",
    studentId: "S2024001",
    type: "document",
    submitted: "2 hours ago",
    status: "pending",
    priority: "high",
    documents: 3,
  },
  {
    id: 2,
    studentName: "Jane Smith",
    studentId: "S2024002",
    type: "payment",
    submitted: "4 hours ago",
    status: "pending",
    priority: "medium",
    amount: "$1,500",
  },
  {
    id: 3,
    studentName: "Robert Johnson",
    studentId: "S2024003",
    type: "document",
    submitted: "1 day ago",
    status: "pending",
    priority: "low",
    documents: 2,
  },
  {
    id: 4,
    studentName: "Sarah Williams",
    studentId: "S2024004",
    type: "payment",
    submitted: "1 day ago",
    status: "pending",
    priority: "medium",
    amount: "$1,500",
  },
  {
    id: 5,
    studentName: "Michael Brown",
    studentId: "S2024005",
    type: "document",
    submitted: "2 days ago",
    status: "pending",
    priority: "low",
    documents: 4,
  },
  {
    id: 6,
    studentName: "Emily Davis",
    studentId: "S2024006",
    type: "document",
    submitted: "30 minutes ago",
    status: "pending",
    priority: "high",
    documents: 5,
  },
  {
    id: 7,
    studentName: "David Wilson",
    studentId: "S2024007",
    type: "payment",
    submitted: "1 hour ago",
    status: "pending",
    priority: "high",
    amount: "$2,000",
  },
  {
    id: 8,
    studentName: "Lisa Anderson",
    studentId: "S2024008",
    type: "document",
    submitted: "3 hours ago",
    status: "pending",
    priority: "medium",
    documents: 2,
  },
  {
    id: 9,
    studentName: "James Taylor",
    studentId: "S2024009",
    type: "payment",
    submitted: "5 hours ago",
    status: "pending",
    priority: "low",
    amount: "$1,200",
  },
  {
    id: 10,
    studentName: "Patricia Martinez",
    studentId: "S2024010",
    type: "document",
    submitted: "6 hours ago",
    status: "pending",
    priority: "medium",
    documents: 3,
  },
  {
    id: 11,
    studentName: "Christopher Garcia",
    studentId: "S2024011",
    type: "payment",
    submitted: "12 hours ago",
    status: "pending",
    priority: "high",
    amount: "$1,800",
  },
  {
    id: 12,
    studentName: "Jennifer Rodriguez",
    studentId: "S2024012",
    type: "document",
    submitted: "1 day ago",
    status: "pending",
    priority: "low",
    documents: 1,
  },
  {
    id: 13,
    studentName: "Matthew Lee",
    studentId: "S2024013",
    type: "payment",
    submitted: "2 days ago",
    status: "pending",
    priority: "medium",
    amount: "$1,500",
  },
  {
    id: 14,
    studentName: "Linda Harris",
    studentId: "S2024014",
    type: "document",
    submitted: "3 days ago",
    status: "pending",
    priority: "low",
    documents: 3,
  },
  {
    id: 15,
    studentName: "Daniel Clark",
    studentId: "S2024015",
    type: "payment",
    submitted: "3 days ago",
    status: "pending",
    priority: "low",
    amount: "$1,000",
  },
];
